# Configuration sp√©cifique pour Docker
# Utilise les noms de containers au lieu de localhost

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/user_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/testai
          jwk-set-uri: http://keycloak:8080/realms/testai/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://keycloak:8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true